-- Database: SmartHomeTEC

CREATE TABLE ADMINISTRADOR(
Email VARCHAR(30),
Passw VARCHAR(16),
Disp_region VARCHAR(15),
Pro_disp_usu VARCHAR(15),
Disp_gest VARCHAR(15),
PRIMARY KEY(Email)
);

CREATE TABLE L_DIST(
Ademail VARCHAR(30),
Dist VARCHAR(30),
PRIMARY KEY(Ademail)
);

CREATE TABLE L_DISP_TOTAL(
Ademail VARCHAR(30),
Disp_total VARCHAR(30),
PRIMARY KEY(Ademail)
);
CREATE TABLE L_DISP_REGION(
Ademail VARCHAR(30),
Disp_region VARCHAR(30),
PRIMARY KEY(Ademail)
);

CREATE TABLE CLIENTE(
Nombre VARCHAR(15),
Aposento VARCHAR(15),
Continente VARCHAR(20),
Pais VARCHAR(20),
Email VARCHAR(30),
Passw VARCHAR(16),
PRIMARY KEY(Email)
);

CREATE TABLE APELLIDO(
Clemail VARCHAR(30),
Apellido VARCHAR(30),
PRIMARY KEY(Clemail)
);

CREATE TABLE DIRECCION(
Clemail VARCHAR(30),
Direccion VARCHAR(30),
PRIMARY KEY(Clemail)
);


CREATE TABLE DISPOSITIVO(
Nombre VARCHAR(15),
Informacion VARCHAR(45),
Marca VARCHAR(20),
Tipo VARCHAR(30),
Garantia VARCHAR(30),
Serie VARCHAR(13),
Consumo INT,
PRIMARY KEY(Serie)
);

CREATE TABLE L_ON(
Dserie VARCHAR(13),
L_on TIMESTAMP,
PRIMARY KEY(Dserie)
);

CREATE TABLE L_USUARIO(
Dserie VARCHAR(13),
Direccion VARCHAR(30),
PRIMARY KEY(Dserie)
);

CREATE TABLE DISTRIBUIDOR(
Ced_jurid INT,
Region VARCHAR(20),
Nombre VARCHAR(15),
Admin_email VARCHAR(30),
PRIMARY KEY(Ced_jurid),
FOREIGN KEY(Admin_email) REFERENCES ADMINISTRADOR(Email)
);

------------ REVISAR CONTEXTO CON LA KEY
CREATE TABLE PEDIDO(
Dispositivo VARCHAR(15),
Consecutivo VARCHAR(30),
Clemail VARCHAR(30),
PRIMARY KEY(Clemail)
);

CREATE TABLE APOSENTO(
Nombre VARCHAR(30),
Clemail VARCHAR(30),
PRIMARY KEY(Clemail)
);

CREATE TABLE DISPOSITIVO_APOSENTO(
Dispositivo_apo VARCHAR(30),
Clemail VARCHAR(30),
PRIMARY KEY(Clemail)
);
---------------------------------------------------
CREATE TABLE FACTURA(
No_fact INT,
F_compra TIMESTAMP,
Tip_disposit VARCHAR(15),
Precio INT,
Clemail VARCHAR(30),
PRIMARY KEY (No_fact),
FOREIGN KEY (Clemail) REFERENCES PEDIDO(Clemail)
);

CREATE TABLE GARANTIA(
No_serie INT,
F_compra TIMESTAMP,
F_vence TIMESTAMP,
Dispserie VARCHAR(13),
PRIMARY KEY (No_serie),
FOREIGN KEY (Dispserie) REFERENCES DISPOSITIVO(Serie)
);

CREATE TABLE TIPODISPOSITIVO(
Tipo VARCHAR(20),
Dispserie VARCHAR(13),
PRIMARY KEY (Dispserie)
);

ALTER TABLE GARANTIA
ADD CONSTRAINT GARANTIA_DISPOSITIVO_FK FOREIGN KEY (Dispserie)
REFERENCES DISPOSITIVO(Serie);

ALTER TABLE FACTURA
ADD CONSTRAINT FACTURA_PEDIDO_FK FOREIGN KEY (Clemail)
REFERENCES PEDIDO(Clemail);

ALTER TABLE DISTRIBUIDOR
ADD CONSTRAINT DISTRIBUIDOR_ADMINISTRADOR_FK FOREIGN KEY (Admin_email)
REFERENCES ADMINISTRADOR(Email);



	